{
 "title": "Node Stats",
 "tags": [
  "linux",
  "node_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Host", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (node_uname_info{job=~\"$job\"}) by (release)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-node_boot_time_seconds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode=\"user\",job=~\"$job\"}[2m])",
     "legendFormat": "{{job}} core{{cpu}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"$job\"}",
     "legendFormat": "{{job}} 1 min avg"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "{{job}} 5 min avg"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=~\"/dev/.*\",mountpoint!=\"/nix/store\",job=~\"$job\"} - node_filesystem_free_bytes{job=~\"$job\"}) / node_filesystem_size_bytes{device=~\"/dev/.*\",mountpoint!=\"/nix/store\",job=~\"$job\"}",
     "legendFormat": "{{job}} {{mountpoint}} used"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"}) / node_memory_MemTotal_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}} used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\",device!=\"lo\"}[2m])) by (job)",
     "legendFormat": "{{job}} rx"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\",device!=\"lo\"}[2m])) by (job)",
     "legendFormat": "{{job}} tx"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{job=~\"$job\"}",
     "legendFormat": "{{job}} {{device}}"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~\"$job\"} - node_memory_SwapFree_bytes{job=~\"$job\"}) / node_memory_SwapTotal_bytes{job=~\"$job\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg(node_cpu_scaling_frequency_hertz{job=~\"$job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "max(node_hwmon_curr_amps{job=~\"$job\"}) by (job) * max(node_hwmon_in_volts{job=~\"$job\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=~\"$job\"}",
     "legendFormat": "{{ job }} {{ sensor }}"
    }
   ]
  }
 ]
}